function betas = betaCorrespondence_Group()
%
%  betaCorrespondence.m is a simple function which should combine
%  three things: preBeta:	a string which is at the start of each file
%  containing a beta image, betas:	a struct indexed by (session,
%  condition) containing a sting unique to each beta image, postBeta:	a
%  string which is at the end of each file containing a beta image, not
%  containing the file .suffix
% 
%  use "[[subjectName]]" as a placeholder for the subject's name as found
%  in userOptions.subjectNames if necessary For example, in an experment
%  where the data from subject1 (subject1 name)  is saved in the format:
%  subject1Name_session1_condition1_experiment1.img and similarly for the
%  other conditions, one could use this function to define a general
%  mapping from experimental conditions to the path where the brain
%  responses are stored. If the paths are defined for a general subject,
%  the term [[subjectName]] would be iteratively replaced by the subject
%  names as defined by userOptions.subjectNames.
% 
%  note that this function could be replaced by an explicit mapping from
%  experimental conditions and sessions to data paths.
% 
%  Cai Wingfield 1-2010
%__________________________________________________________________________
% Copyright (C) 2010 Medical Research Council

preBeta = '';

% betas(session, condition).identifier = ???
all_conds={ ...
'sentence_touch', ...
'sentence_light', ...
'sentence_hit', ...
'sentence_crush', ...
'sentence_kiss', ...
'sentence_stretch', ...
'sentence_kick', ...
'sentence_console', ...
'picture_touch', ...
'picture_light', ...
'picture_hit', ...
'picture_crush', ...
'picture_kiss', ...
'picture_stretch', ...
'picture_kick', ...
'picture_console', ...
'sentence_act_can', ...
'sentence_act_rel', ...
'sentence_pass_can', ...
'sentence_pass_rel', ...
'picture_act_can', ...
'picture_act_rel', ...
'picture_pass_can', ...
'picture_pass_rel', ...
'sentence_anim', ...
'sentence_inanim', ...
'picture_anim', ...
'picture_inanim'
};

for i = 1:length(all_conds)
    betas(1,i).identifier=all_conds{i};
end
% betas(1,1).identifier = 'session1_condition1';
% betas(1,2).identifier = 'session1_condition2';
% betas(1,3).identifier = 'session1_condition3';
% betas(1,4).identifier = 'session1_condition4';
% betas(1,5).identifier = 'session1_condition5';
% betas(1,6).identifier = 'session1_condition6';
% betas(1,7).identifier = 'session1_condition7';
% betas(1,8).identifier = 'session1_condition8';

postBeta = '.img';

for session = 1:size(betas,1)
	for condition = 1:size(betas,2)
		betas(session,condition).identifier = [preBeta betas(session,condition).identifier postBeta];
	end%for
end%for