function betas = betaCorrespondence_LSA()
%
%  betaCorrespondence.m is a simple function which should combine
%  three things: preBeta:	a string which is at the start of each file
%  containing a beta image, betas:	a struct indexed by (session,
%  condition) containing a sting unique to each beta image, postBeta:	a
%  string which is at the end of each file containing a beta image, not
%  containing the file .suffix
% 
%  use "[[subjectName]]" as a placeholder for the subject's name as found
%  in userOptions.subjectNames if necessary For example, in an experment
%  where the data from subject1 (subject1 name)  is saved in the format:
%  subject1Name_session1_condition1_experiment1.img and similarly for the
%  other conditions, one could use this function to define a general
%  mapping from experimental conditions to the path where the brain
%  responses are stored. If the paths are defined for a general subject,
%  the term [[subjectName]] would be iteratively replaced by the subject
%  names as defined by userOptions.subjectNames.
% 
%  note that this function could be replaced by an explicit mapping from
%  experimental conditions and sessions to data paths.
% 
%  Cai Wingfield 1-2010
%__________________________________________________________________________
% Copyright (C) 2010 Medical Research Council

preBeta = '';

% betas(session, condition).identifier = ???
all_conds={ ...
's_Touch_Pass_Rel', ...
's_Touch_Pass_Can', ...
's_Touch_Act_Rel', ...
's_Touch_Act_Can', ...
's_Stretch_Pass_Rel', ...
's_Stretch_Pass_Can', ...
's_Stretch_Act_Rel', ...
's_Stretch_Act_Can', ...
's_Light_Pass_Rel', ...
's_Light_Pass_Can', ...
's_Light_Act_Rel', ...
's_Light_Act_Can', ...
's_Hit_Pass_Rel', ...
's_Hit_Pass_Can', ...
's_Hit_Act_Rel', ...
's_Hit_Act_Can', ...
's_Crush_Pass_Rel', ...
's_Crush_Pass_Can', ...
's_Crush_Act_Rel', ...
's_Crush_Act_Can', ...
's_Kiss_Pass_Rel', ...
's_Kiss_Pass_Can', ...
's_Kiss_Act_Rel', ...
's_Kiss_Act_Can', ...
's_Stretch_Pass_Rel', ...
's_Stretch_Pass_Can', ...
's_Stretch_Act_Rel', ...
's_Stretch_Act_Can', ...
's_Kick_Pass_Rel', ...
's_Kick_Pass_Can', ...
's_Kick_Act_Rel', ...
's_Kick_Act_Can', ...
's_Console_Pass_Rel', ...
's_Console_Pass_Can', ...
's_Console_Act_Rel', ...
's_Console_Act_Can', ...
'l_Touch_Pass_Rel', ...
'l_Touch_Pass_Can', ...
'l_Touch_Act_Rel', ...
'l_Touch_Act_Can', ...
'l_Light_Pass_Rel', ...
'l_Light_Pass_Can', ...
'l_Light_Act_Rel', ...
'l_Light_Act_Can', ...
'l_Hit_Pass_Rel', ...
'l_Hit_Pass_Can', ...
'l_Hit_Act_Rel', ...
'l_Hit_Act_Can', ...
'l_Crush_Pass_Rel', ...
'l_Crush_Pass_Can', ...
'l_Crush_Act_Rel', ...
'l_Crush_Act_Can', ...
'l_Kiss_Pass_Rel', ...
'l_Kiss_Pass_Can', ...
'l_Kiss_Act_Rel', ...
'l_Kiss_Act_Can', ...
'l_Stretch_Pass_Rel', ...
'l_Stretch_Pass_Can', ...
'l_Stretch_Act_Rel', ...
'l_Stretch_Act_Can', ...
'l_Kick_Pass_Rel', ...
'l_Kick_Pass_Can', ...
'l_Kick_Act_Rel', ...
'l_Kick_Act_Can', ...
'l_Console_Pass_Rel', ...
'l_Console_Pass_Can', ...
'l_Console_Act_Rel', ...
'l_Console_Act_Can' ...
};

for i = 1:length(all_conds)
    betas(1,i).identifier=all_conds{i};
end
% betas(1,1).identifier = 'session1_condition1';
% betas(1,2).identifier = 'session1_condition2';
% betas(1,3).identifier = 'session1_condition3';
% betas(1,4).identifier = 'session1_condition4';
% betas(1,5).identifier = 'session1_condition5';
% betas(1,6).identifier = 'session1_condition6';
% betas(1,7).identifier = 'session1_condition7';
% betas(1,8).identifier = 'session1_condition8';

postBeta = '.img';

for session = 1:size(betas,1)
	for condition = 1:size(betas,2)
		betas(session,condition).identifier = [preBeta betas(session,condition).identifier postBeta];
	end%for
end%for