pathName='../LanguageMVPA/stimuli/';
imageNames={
'l_Touch_Touch_Inanim_Pass_Rel', ...
'l_Stretch_ChState_Anim_Pass_Rel', ...
'l_Light_ChState_Inanim_Pass_Rel', ...
'l_Kiss_Touch_Anim_Pass_Rel', ...
'l_Kick_Impact_Anim_Pass_Rel', ...
'l_Hit_Impact_Inanim_Pass_Rel', ...
'l_Crush_Psych_Inanim_Pass_Rel', ...
'l_Console_Psych_Anim_Pass_Rel', ...
'l_Touch_Touch_Inanim_Pass_Can', ...
'l_Stretch_ChState_Anim_Pass_Can', ...
'l_Light_ChState_Inanim_Pass_Can', ...
'l_Kiss_Touch_Anim_Pass_Can', ...
'l_Kick_Impact_Anim_Pass_Can', ...
'l_Hit_Impact_Inanim_Pass_Can', ...
'l_Crush_Psych_Inanim_Pass_Can', ...
'l_Console_Psych_Anim_Pass_Can', ...
'l_Touch_Touch_Inanim_Act_Rel', ...
'l_Stretch_ChState_Anim_Act_Rel', ...
'l_Light_ChState_Inanim_Act_Rel', ...
'l_Kiss_Touch_Anim_Act_Rel', ...
'l_Kick_Impact_Anim_Act_Rel', ...
'l_Hit_Impact_Inanim_Act_Rel', ...
'l_Crush_Psych_Inanim_Act_Rel', ...
'l_Console_Psych_Anim_Act_Rel', ...
'l_Touch_Touch_Inanim_Act_Can', ...
'l_Stretch_ChState_Anim_Act_Can', ...
'l_Light_ChState_Inanim_Act_Can', ...
'l_Kiss_Touch_Anim_Act_Can', ...
'l_Kick_Impact_Anim_Act_Can', ...
'l_Hit_Impact_Inanim_Act_Can', ...
'l_Crush_Psych_Inanim_Act_Can', ...
'l_Console_Psych_Anim_Act_Can'


};

nimsx=4;
nimsy=8;
cutx=200;
cuty=150;
D=nimsx*nimsy;
%size is 2007x2400
    currImage=imread([pathName imageNames{1} '.jpg']);
    currImage=imresize(currImage(cutx:2001-cutx,cuty:2400-cuty,1), .1);
    currImage=(currImage>0);
    %extract cx cy
    [ny nx] = size(currImage);
    W=nx*ny;
for i = 1:length(imageNames)
    currImage=imread([pathName imageNames{i} '.jpg']);
    currImage=imresize(currImage(cutx:2001-cutx,cuty:2400-cuty,1), .1);
    currImage=(currImage>0);
    
    ims(i,:)=reshape(currImage,1,W);
end
ims=uint8(ims);
save('lmvpa/lmvpa_pictures.mat', 'W', 'ims', 'nx', 'ny', 'nimsx', 'nimsy', 'D');